.TH fastq-trim 1
.SH NAME    \" Section header
.PP
 
fastq-trim - Trim adapters and low-quality bases from FASTQ files

\" Convention:
\" Underline anything that is typed verbatim - commands, etc.
.SH SYNOPSIS
.PP
.nf 
.na 
fastq-trim file.fastq[.gz|.bz2|.xz]
.ad
.fi

.SH OPTIONS
.TP
\fB\-\-\flagfR[=\fIparameter\fR]
description

.SH "DESCRIPTION"

.B Fastq-trim
removes adapters and low-quality bases from a FASTQ file.

.SH "SEE ALSO"
biolibc(3)

.SH BUGS
Please report bugs to the author and send patches in unified diff format.
(man diff for more information)

.SH AUTHOR
.nf
.na
J. Bacon
