    
/*
 *  Generated by ./auto-gen-get-set
 *
 *  Accessor macros.  Use these to access structure members from functions
 *  outside the fastq_trim_t class.
 *
 *  These generated macros are not expected to be perfect.  Check and edit
 *  as needed before adding to your code.
 */

#define FASTQ_TRIM_VERBOSE(ptr)         ((ptr)->verbose)
#define FASTQ_TRIM_ADAPTER_MATCH_FUNCTION(ptr) ((ptr)->adapter_match_function)
#define FASTQ_TRIM_INFILE1(ptr)         ((ptr)->infile1)
#define FASTQ_TRIM_OUTFILE1(ptr)        ((ptr)->outfile1)
#define FASTQ_TRIM_INFILE2(ptr)         ((ptr)->infile2)
#define FASTQ_TRIM_OUTFILE2(ptr)        ((ptr)->outfile2)
#define FASTQ_TRIM_INSTREAM1(ptr)       ((ptr)->instream1)
#define FASTQ_TRIM_OUTSTREAM1(ptr)      ((ptr)->outstream1)
#define FASTQ_TRIM_INSTREAM2(ptr)       ((ptr)->instream2)
#define FASTQ_TRIM_OUTSTREAM2(ptr)      ((ptr)->outstream2)
#define FASTQ_TRIM_ADAPTER1(ptr)        ((ptr)->adapter1)
#define FASTQ_TRIM_ADAPTER1_AE(ptr,c)   ((ptr)->adapter1[c])
#define FASTQ_TRIM_ADAPTER2(ptr)        ((ptr)->adapter2)
#define FASTQ_TRIM_ADAPTER2_AE(ptr,c)   ((ptr)->adapter2[c])
#define FASTQ_TRIM_MIN_LENGTH(ptr)      ((ptr)->min_length)
#define FASTQ_TRIM_MIN_MATCH(ptr)       ((ptr)->min_match)
#define FASTQ_TRIM_POLYA_MIN_LEN(ptr)   ((ptr)->polya_min_len)
#define FASTQ_TRIM_MAX_MISMATCH_PERCENT(ptr) ((ptr)->max_mismatch_percent)
#define FASTQ_TRIM_MIN_QUAL(ptr)        ((ptr)->min_qual)
#define FASTQ_TRIM_PHRED_BASE(ptr)      ((ptr)->phred_base)
