fastq-trim-class.o: fastq-trim-class.c fastq-trim.h fastq-trim-rvs.h \
  fastq-trim-accessors.h fastq-trim-mutators.h
	${CC} -c ${CFLAGS} fastq-trim-class.c

fastq-trim-mutators.o: fastq-trim-mutators.c fastq-trim.h \
  fastq-trim-rvs.h fastq-trim-accessors.h fastq-trim-mutators.h
	${CC} -c ${CFLAGS} fastq-trim-mutators.c

fastq-trim.o: fastq-trim.c fastq-trim.h fastq-trim-rvs.h \
  fastq-trim-accessors.h fastq-trim-mutators.h
	${CC} -c ${CFLAGS} fastq-trim.c

