    
/*
 *  Generated by ./auto-gen-get-set
 *
 *  Accessor macros.  Use these to access structure members from functions
 *  outside the trim_t class.
 *
 *  These generated macros are not expected to be perfect.  Check and edit
 *  as needed before adding to your code.
 */

#define TRIM_INFILE1(ptr)               ((ptr)->infile1)
#define TRIM_INFILE1_AE(ptr,c)          ((ptr)->infile1[c])
#define TRIM_OUTFILE1(ptr)              ((ptr)->outfile1)
#define TRIM_OUTFILE1_AE(ptr,c)         ((ptr)->outfile1[c])
#define TRIM_INFILE2(ptr)               ((ptr)->infile2)
#define TRIM_INFILE2_AE(ptr,c)          ((ptr)->infile2[c])
#define TRIM_OUTFILE2(ptr)              ((ptr)->outfile2)
#define TRIM_OUTFILE2_AE(ptr,c)         ((ptr)->outfile2[c])
#define TRIM_INSTREAM1(ptr)             ((ptr)->instream1)
#define TRIM_INSTREAM1_AE(ptr,c)        ((ptr)->instream1[c])
#define TRIM_OUTSTREAM1(ptr)            ((ptr)->outstream1)
#define TRIM_OUTSTREAM1_AE(ptr,c)       ((ptr)->outstream1[c])
#define TRIM_INSTREAM2(ptr)             ((ptr)->instream2)
#define TRIM_INSTREAM2_AE(ptr,c)        ((ptr)->instream2[c])
#define TRIM_OUTSTREAM2(ptr)            ((ptr)->outstream2)
#define TRIM_OUTSTREAM2_AE(ptr,c)       ((ptr)->outstream2[c])
#define TRIM_ADAPTER(ptr)               ((ptr)->adapter)
#define TRIM_ADAPTER_AE(ptr,c)          ((ptr)->adapter[c])
#define TRIM_MIN_LENGTH(ptr)            ((ptr)->min_length)
#define TRIM_MIN_MATCH(ptr)             ((ptr)->min_match)
#define TRIM_MIN_QUAL(ptr)              ((ptr)->min_qual)
#define TRIM_VERBOSE(ptr)               ((ptr)->verbose)
