    
/*
 *  Generated by /usr/local/bin/auto-gen-get-set
 *
 *  Accessor macros.  Use these to access structure members from functions
 *  outside the trim_t class.
 *
 *  These generated macros are not expected to be perfect.  Check and edit
 *  as needed before adding to your code.
 */

#define TRIM_VERBOSE(ptr)               ((ptr)->verbose)
#define TRIM_ADAPTER_MATCH_FUNCTION(ptr) ((ptr)->adapter_match_function)
#define TRIM_INFILE1(ptr)               ((ptr)->infile1)
#define TRIM_INFILE1_AE(ptr,c)          ((ptr)->infile1[c])
#define TRIM_OUTFILE1(ptr)              ((ptr)->outfile1)
#define TRIM_OUTFILE1_AE(ptr,c)         ((ptr)->outfile1[c])
#define TRIM_INFILE2(ptr)               ((ptr)->infile2)
#define TRIM_INFILE2_AE(ptr,c)          ((ptr)->infile2[c])
#define TRIM_OUTFILE2(ptr)              ((ptr)->outfile2)
#define TRIM_OUTFILE2_AE(ptr,c)         ((ptr)->outfile2[c])
#define TRIM_INSTREAM1(ptr)             ((ptr)->instream1)
#define TRIM_INSTREAM1_AE(ptr,c)        ((ptr)->instream1[c])
#define TRIM_OUTSTREAM1(ptr)            ((ptr)->outstream1)
#define TRIM_OUTSTREAM1_AE(ptr,c)       ((ptr)->outstream1[c])
#define TRIM_INSTREAM2(ptr)             ((ptr)->instream2)
#define TRIM_INSTREAM2_AE(ptr,c)        ((ptr)->instream2[c])
#define TRIM_OUTSTREAM2(ptr)            ((ptr)->outstream2)
#define TRIM_OUTSTREAM2_AE(ptr,c)       ((ptr)->outstream2[c])
#define TRIM_ADAPTER1(ptr)              ((ptr)->adapter1)
#define TRIM_ADAPTER1_AE(ptr,c)         ((ptr)->adapter1[c])
#define TRIM_ADAPTER2(ptr)              ((ptr)->adapter2)
#define TRIM_ADAPTER2_AE(ptr,c)         ((ptr)->adapter2[c])
#define TRIM_MIN_LENGTH(ptr)            ((ptr)->min_length)
#define TRIM_MIN_MATCH(ptr)             ((ptr)->min_match)
#define TRIM_POLYA_MIN_LEN(ptr)         ((ptr)->polya_min_len)
#define TRIM_MAX_MISMATCH_PERCENT(ptr)  ((ptr)->max_mismatch_percent)
#define TRIM_MIN_QUAL(ptr)              ((ptr)->min_qual)
#define TRIM_PHRED_BASE(ptr)            ((ptr)->phred_base)
